eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka
management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
spring:
    kafka:
        bootstrap-servers: broker:29092
    redis:
        host: redis
        port: 6379
