eureka:
    instance:
        prefer-ip-address: true
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    tracing:
        sampling:
            probability: 1
server:
    port: 0
spring:
    application:
        name: notification-service
    kafka:
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: '*'
                        type:
                            mapping: verification:com.microservice.notificationservice.VerificationEvent,
                                event:com.microservice.notificationservice.RequestPlacedEvent
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        producer:
            properties:
                spring:
                    json:
                        add:
                            type:
                                headers: false
    mail:
        host: smtp.gmail.com
        password: idvmhmrrypozlliq
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: dungtestemail33@gmail.com
