eureka:
    instance:
        prefer-ip-address: true
fullstack:
    app:
        jwtCookieName: cookie
        jwtExpirationMs: 86400000
        jwtSecret: ======================fullstack=Spring===========================
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        circuitbreakers:
            enabled: true
        ratelimiters:
            enabled: true
    tracing:
        sampling:
            probability: 1.0
resilience4j:
    circuitbreaker:
        instances:
            user:
                automaticTransitionFromOpenToHalfOpenEnabled: true
                event-consumer-buffer-size: 10
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 3
                registerHealthIndicator: true
                slidingWindowSize: 5
                slidingWindowType: COUNT_BASED
                waitDurationInOpenState: 5s
    retry:
        instances:
            user:
                max-attempts: 3
                wait-duration: 5s
    timelimiter:
        instances:
            user:
                timeout-duration: 5s
server:
    error:
        include-message: always
    port: ${PORT:8081}
spring:
    aop:
        proxy-target-class: true
    application:
        name: device-service
    cache:
        type: REDIS
    data:
        redis:
            repositories:
                type: none
    flyway:
        baseline-on-migrate: true
        enabled: true
        validate-on-migrate: false
    jpa:
        defer-datasource-initialization: false
    redis:
        cache-null-values: false
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    sql:
        init:
            data-locations: classpath:/data/mysql/data.sql
            mode: never
    time-to-live: 60000
springdoc:
    swagger-ui:
        tagsSorter: alpha
