eureka:
    instance:
        prefer-ip-address: true
fullstack:
    app:
        jwtCookieName: cookie
        jwtExpirationMs: 86400000
        jwtSecret: ======================fullstack=Spring===========================
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    tracing:
        sampling:
            probability: 1.0
server:
    error:
        include-message: always
    port: ${PORT:8084}
spring:
    aop:
        proxy-target-class: true
    application:
        name: keeper-order-service
    cache:
        type: REDIS
    data:
        redis:
            repositories:
                type: none
    flyway:
        baseline-on-migrate: true
        enabled: false
        validate-on-migrate: false
    jpa:
        defer-datasource-initialization: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                format_sql: true
    redis:
        cache-null-values: false
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    sql:
        init:
            data-locations: classpath:/data/mysql/data.sql
            mode: never
    time-to-live: 60000
