eureka:
    instance:
        prefer-ip-address: true
fullstack:
    app:
        jwtCookieName: cookie
        jwtExpirationMs: 86400000
        jwtSecret: ======================fullstack=Spring===========================
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    tracing:
        sampling:
            probability: 1.0
server:
    error:
        include-message: always
    port: ${PORT:8082}
spring:
    aop:
        proxy-target-class: true
    application:
        name: user-service
    flyway:
        baseline-on-migrate: true
        enabled: false
        validate-on-migrate: false
    jpa:
        defer-datasource-initialization: false
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
    kafka:
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                spring:
                    json:
                        type:
                            mapping: verification:com.fullstack.Backend.event.VerificationEvent
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        template:
            default-topic: verificationTopic
    mail:
        host: smtp.gmail.com
        password: idvmhmrrypozlliq
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: dungtestemail33@gmail.com
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    sql:
        init:
            data-locations: classpath:/data/mysql/data.sql
            mode: never
springdoc:
    swagger-ui:
        tagsSorter: alpha
