app:
    client:
        baseUrl: https://dungnguyen69.github.io/Frontend-DeviceManagement
eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka
management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ''
        url: ''
        username: ''
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
    kafka:
        bootstrap-servers: broker:29092
    redis:
        host: redis
        port: 6379
