server:
    port: 8082
spring:
    datasource:
        password: 123456789
        url: jdbc:mysql://mysql:3306/devicemanagementdb
        username: root
    kafka:
        bootstrap-servers: broker:29092
    redis:
        host: redis
