eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    instance:
        hostname: localhost
        prefer-ip-address: true
    password: password
    username: username
logging:
    level:
        org:
            springframework:
                security: DEBUG
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    tracing:
        sampling:
            probability: 1.0
server:
    port: 8761
spring:
    application:
        name: discovery-server
